# Generated by Django 4.1.3 on 2022-11-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
