# Generated by Django 4.1.3 on 2022-11-18 08:36

import api.rent_request.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_request', '0002_alter_rentrequest_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=api.rent_request.models.get_expried, null=True),
        ),
    ]
