# Generated by Django 4.1.3 on 2022-11-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_request', '0003_alter_rentrequest_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrequest',
            name='isConfirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentrequest',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
