# Generated by Django 4.1.3 on 2022-11-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_house_alter_room_status'),
        ('rent_request', '0004_rentrequest_isconfirm_rentrequest_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentrequest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_request', to='room.room'),
        ),
    ]
