# Generated by Django 4.1.3 on 2022-11-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_request', '0003_alter_rentrequest_expires_at'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rentRequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_request.rentrequest'),
        ),
    ]
