# Generated by Django 4.1.3 on 2022-11-16 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('area', models.IntegerField()),
                ('rentPrice', models.IntegerField()),
                ('waterPrice', models.IntegerField()),
                ('electricPrice', models.IntegerField()),
                ('servicePrice', models.IntegerField()),
                ('detail', models.TextField(null=True)),
                ('status', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='room/%Y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house')),
            ],
            options={
                'unique_together': {('name', 'house')},
            },
        ),
    ]
