# Generated by Django 4.1.3 on 2022-11-17 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_landlord'),
        ('room', '0002_room_totalprice_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='house.house'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(default='available', max_length=250),
        ),
    ]
