# Generated by Django 4.1.3 on 2022-11-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgetPasswordToken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
