# Generated by Django 4.1.3 on 2022-12-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_forgetpasswordtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='linkfb',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkin',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkli',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linktw',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
